// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	"github.com/operator-framework/api/pkg/operators/v1alpha1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CSVTestResult) DeepCopyInto(out *CSVTestResult) {
	*out = *in
	if in.CSVRequirementStatus != nil {
		in, out := &in.CSVRequirementStatus, &out.CSVRequirementStatus
		*out = make([]v1alpha1.RequirementStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CSVTestResult.
func (in *CSVTestResult) DeepCopy() *CSVTestResult {
	if in == nil {
		return nil
	}
	out := new(CSVTestResult)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Cnfoperators) DeepCopyInto(out *Cnfoperators) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Cnfoperators.
func (in *Cnfoperators) DeepCopy() *Cnfoperators {
	if in == nil {
		return nil
	}
	out := new(Cnfoperators)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Cnfoperators) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnfoperatorsList) DeepCopyInto(out *CnfoperatorsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Cnfoperators, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnfoperatorsList.
func (in *CnfoperatorsList) DeepCopy() *CnfoperatorsList {
	if in == nil {
		return nil
	}
	out := new(CnfoperatorsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CnfoperatorsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnfoperatorsSpec) DeepCopyInto(out *CnfoperatorsSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnfoperatorsSpec.
func (in *CnfoperatorsSpec) DeepCopy() *CnfoperatorsSpec {
	if in == nil {
		return nil
	}
	out := new(CnfoperatorsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CnfoperatorsStatus) DeepCopyInto(out *CnfoperatorsStatus) {
	*out = *in
	in.CSV.DeepCopyInto(&out.CSV)
	out.Deployment = in.Deployment
	out.Operators = in.Operators
	if in.Operands != nil {
		in, out := &in.Operands, &out.Operands
		*out = make([]TestResult, len(*in))
		copy(*out, *in)
	}
	if in.CRDS != nil {
		in, out := &in.CRDS, &out.CRDS
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	if in.PodNames != nil {
		in, out := &in.PodNames, &out.PodNames
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CnfoperatorsStatus.
func (in *CnfoperatorsStatus) DeepCopy() *CnfoperatorsStatus {
	if in == nil {
		return nil
	}
	out := new(CnfoperatorsStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TestResult) DeepCopyInto(out *TestResult) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TestResult.
func (in *TestResult) DeepCopy() *TestResult {
	if in == nil {
		return nil
	}
	out := new(TestResult)
	in.DeepCopyInto(out)
	return out
}
