# permissions for end users to view cnfoperators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnfoperators-viewer-role
rules:
- apiGroups:
  - test.cnf.operators.com
  resources:
  - cnfoperators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.cnf.operators.com
  resources:
  - cnfoperators/status
  verbs:
  - get
